apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oficina
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
  - name: oficina-api
    newName: 857145323352.dkr.ecr.us-east-1.amazonaws.com/oficina-dgcar-16soat/oficina-api
    newTag: latest
